# Generated by Django 5.2.8 on 2025-11-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        ('users', '0004_userprofile_average_rating_userprofile_total_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del Cupón')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentaje'), ('FIXED', 'Monto Fijo')], max_length=20, verbose_name='Tipo de Descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor del Descuento')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Máximo de Descuento (para porcentaje)')),
                ('valid_from', models.DateTimeField(verbose_name='Válido Desde')),
                ('valid_to', models.DateTimeField(verbose_name='Válido Hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('max_uses', models.PositiveIntegerField(default=1000, verbose_name='Usos Totales Máximos')),
                ('uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Usos por Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Código de Promoción',
                'verbose_name_plural': 'Códigos de Promoción',
            },
        ),
        migrations.CreateModel(
            name='UserPromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promocode')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='users.userprofile')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_code_usage', to='travel.viaje')),
            ],
            options={
                'verbose_name': 'Uso de Cupón',
                'verbose_name_plural': 'Usos de Cupones',
            },
        ),
    ]
