# Generated by Django 5.2.8 on 2025-11-10 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Lugar (ej. Casa)')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Nombre del Ícono (ej. 'home', 'work')")),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Ubicación Guardada',
                'verbose_name_plural': 'Ubicaciones Guardadas',
            },
        ),
    ]
