# Generated by Django 5.2.8 on 2025-11-10 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersavedlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('EFECTIVO', 'Efectivo')], max_length=20, unique=True, verbose_name='Nombre del Método')),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Ícono')),
            ],
            options={
                'verbose_name': 'Tipo de Método de Pago',
                'verbose_name_plural': 'Tipos de Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo (ej. Visa Personal)')),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca (Visa, Mastercard)')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos')),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token de Pago')),
                ('identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador (ej. N° de Yape)')),
                ('is_default', models.BooleanField(default=False, verbose_name='¿Es método por defecto?')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_methods', to='users.paymentmethodtype')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Método de Pago de Usuario',
                'verbose_name_plural': 'Métodos de Pago de Usuarios',
                'unique_together': {('user_profile', 'payment_token', 'last_four_digits')},
            },
        ),
    ]
