# Generated by Django 5.2.8 on 2025-11-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentmethodtype_userpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Calificación Promedio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Calificaciones'),
        ),
    ]
