# Generated by Django 5.2.8 on 2025-11-10 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BUSCANDO', 'Buscando Conductor'), ('ACEPTADO', 'Conductor Aceptó'), ('EN_CAMINO', 'Conductor en Camino'), ('EN_PROGRESO', 'Viaje en Progreso'), ('FINALIZADO', 'Viaje Finalizado'), ('CANCELADO', 'Viaje Cancelado')], default='BUSCANDO', max_length=20, verbose_name='Estado del Viaje')),
                ('origen_lat', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitud Origen')),
                ('origen_lng', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitud Origen')),
                ('origen_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección Origen')),
                ('destino_lat', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Latitud Destino')),
                ('destino_lng', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Longitud Destino')),
                ('destino_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección Destino')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Estimado')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_conductor', to='users.userprofile')),
                ('pasajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_pasajero', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-created_at'],
            },
        ),
    ]
