# Generated by Django 5.2.8 on 2025-11-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Teléfono')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('is_active_for_service', models.BooleanField(default=False, verbose_name='¿Activo para servicio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(related_name='users', to='usuarios.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='ProviderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, verbose_name='Nombre de Tienda/Negocio')),
                ('store_address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_data', to='usuarios.userprofile')),
            ],
            options={
                'verbose_name': 'Datos de Proveedor',
                'verbose_name_plural': 'Datos de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de Licencia')),
                ('soat_number', models.CharField(max_length=100, verbose_name='SOAT')),
                ('vehicle_plate', models.CharField(max_length=10, unique=True, verbose_name='Placa del Vehículo')),
                ('vehicle_card', models.CharField(max_length=100, verbose_name='Tarjeta de Propiedad')),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo del Vehículo')),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color del Vehículo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='¿Datos Verificados?')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_data', to='usuarios.userprofile')),
            ],
            options={
                'verbose_name': 'Datos de Conductor',
                'verbose_name_plural': 'Datos de Conductores',
            },
        ),
    ]
