# Generated by Django 5.2.8 on 2025-11-10 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        ('users', '0004_userprofile_average_rating_userprofile_total_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (Estrellas)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.userprofile', verbose_name='Perfil del Reseñado')),
                ('reviewer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='users.userprofile', verbose_name='Perfil del Reseñador')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='travel.viaje', verbose_name='Viaje Asociado')),
            ],
            options={
                'verbose_name': 'Reseña y Calificación',
                'verbose_name_plural': 'Reseñas y Calificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
